### ISSUE TITLE
Permission management

### ISSUE THREAD

**Issue by yabbes** [multiplexd/brightlight#3]
Thanks for your program, it's working great, I've just been dealing with the issue of file permissions, so I was wondering if you had any thoughts about it or a preferred solution for the problem.

I have compiled brightlight and stored the executable somewhere in $PATH. It is typically executed by my own user, but the files it has to access are originally owned by root:
```bash
$ ls -l /sys/class/backlight/intel_backlight/
total 0
-r--r--r-- 1 root root 4096 Mar 30 15:20 actual_brightness
-rw-r--r-- 1 root root 4096 Mar 30 15:20 brightness
-r--r--r-- 1 root root 4096 Mar 30 15:20 max_brightness
```
 I have already changed these file permissions for brightness and max_brightness adding them to my user's group and enabling g+w. I thought this would fix it, but it seems it's only a temporary solution and after each reboot permissions in this directory seem to be reset automatically.

Now brightlight, running under my user, cannot change the files' content anymore.

**Comment by multiplexd** [comment]
Glad to hear it's useful.

My intent is that brightlight would be installed setuid root so that a regular user can manipulate the backlight files at any time, however only now do I realise that this isn't documented. Please see the comments added in commit a656f17 for some more information about ways to allow users to access the necessary sysfs files.

**Comment by yabbes** [comment]
Ah of course! Thank you for your response and I think updating the documentation was very useful. I will modify the binary with setuid now, didn't think of that!
